### ISSUE TITLE
"Entrance" scene Yarn files missing dialogue.

### ISSUE THREAD

**Issue by drdgvhbh** [drdgvhbh/Framed#12]
The `BrokenGlass.json` file current does not have any dialogue. The fallen book does not have a Yarn file currently associated with it. The `FrontDoorNote.json` file uses the same dialogue as `FrontDoor.json`.

**Comment by nyanilee** [comment]
Done, those jsons now have the appropriate dialogue

**Comment by drdgvhbh** [comment]
The fallen book still has no dialogue. See the `book` game object in the ladybug scene.
